import {useEffect,useState} from 'react';
import {LayoutDashboard,MessageCircle,BookOpen,Files,Ticket,ChartNoAxesCombined,Settings as SettingsIcon,FlaskConical,LogOut,Menu,ArrowUpRight,Sparkles,ShieldCheck,ArrowRight} from 'lucide-react';
import {api,send} from './services/api';
import {ErrorBox} from './components/UI';
import {Overview,AnalyticsPage} from './pages/Overview';
import {KnowledgePage} from './pages/Knowledge';
import {DocumentsPage} from './pages/Documents';
import {TicketsPage} from './pages/Tickets';
import {WhatsAppPage,PlaygroundPage,SettingsPage} from './pages/Operations';
const nav=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'whatsapp',label:'WhatsApp',icon:MessageCircle},{id:'knowledge',label:'Knowledge',icon:BookOpen},{id:'documents',label:'Documents',icon:Files},{id:'tickets',label:'Tickets',icon:Ticket},{id:'analytics',label:'Analytics',icon:ChartNoAxesCombined},{id:'settings',label:'Settings',icon:SettingsIcon}];
export function App(){
 const [session,setSession]=useState<{authenticated:boolean;configured:boolean;username:string|null}|null>(null);
 const [page,setPage]=useState(location.hash.slice(1)||'overview');const [sidebar,setSidebar]=useState(false);const [loginError,setLoginError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{api<typeof session>('/auth/session').then(setSession).catch(()=>setLoginError('Backend belum terhubung. Jalankan npm run dev dari folder proyek.'));const handler=()=>setPage(location.hash.slice(1)||'overview');window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler);},[]);
 const navigate=(id:string)=>{location.hash=id;setPage(id);setSidebar(false);};
 if(!session?.authenticated)return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-symbol"><MessageCircle size={25}/></span><span>TIVAsk<span className="brand-dot">.</span></span></div><div><span className="story-kicker">INFORMASI JELAS. LANGKAH PASTI.</span><h1>Percakapan kecil.<br/>Masa depan<br/><em>yang besar.</em></h1><p>Satu pusat kendali untuk membantu calon siswa menemukan informasi yang mereka butuhkan.</p><div className="story-proof"><ShieldCheck size={18}/> Berbasis sumber · Terhubung ke panitia</div></div><span className="story-footer">TIVAsk Control Center / SPMB 2026–2027</span><div className="orbit orbit-one"/><div className="orbit orbit-two"/></section><section className="login-side"><form className="login-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setLoginError('');const f=new FormData(e.currentTarget);try{await send('/auth/login',{username:f.get('username'),password:f.get('password')});setSession(await api('/auth/session'));}catch(e){setLoginError((e as Error).message);}finally{setBusy(false);}}}><span className="mini-label"><Sparkles size={15}/> CONTROL CENTER</span><h2>Selamat datang kembali</h2><p>Masuk untuk mengelola informasi dan percakapan TIVAsk.</p><ErrorBox message={loginError}/>{session&&!session.configured&&<div className="notice">Akun admin belum disiapkan. Jalankan <code>scripts/setup-local.ps1</code> dari PowerShell, lalu muat ulang halaman.</div>}<label>Username<input name="username" autoComplete="username" defaultValue="admin" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="btn primary full" disabled={busy||!!session&&!session.configured}>{busy?'Memeriksa…':'Masuk ke dashboard'}<ArrowRight size={18}/></button><div className="login-note"><ShieldCheck size={14}/> Akses khusus administrator sekolah</div></form><span className="login-bottom">TIVAsk · Asisten informasi SPMB</span></section></div>;
 const active=nav.find(n=>n.id===page);
 return <div className="app-shell">{sidebar&&<button className="sidebar-scrim" aria-label="Tutup navigasi" onClick={()=>setSidebar(false)}/>}<aside className={'sidebar '+(sidebar?'open':'')}><button className="brand brand-button" onClick={()=>navigate('overview')}><span className="brand-symbol"><MessageCircle size={22}/></span><span>TIVAsk<span className="brand-dot">.</span><small>CONTROL CENTER</small></span></button><div className="workspace"><div className="school-avatar">A</div><div><strong>SMKN 1 Adiwerna</strong><span>SPMB 2026 / 2027</span></div><span className="workspace-dot"/></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(n=><button key={n.id} className={'nav-item '+(page===n.id?'active':'')} onClick={()=>navigate(n.id)}><n.icon size={19}/><span>{n.label}</span>{page===n.id&&<i/>}</button>)}</nav><div className="nav-label lab-label">DEVELOPER TOOLS</div><button className={'nav-item '+(page==='playground'?'active':'')} onClick={()=>navigate('playground')}><FlaskConical size={19}/><span>Chat Playground</span><ArrowUpRight size={14}/></button><div className="sidebar-bottom"><div className="sidebar-tip"><span className="tip-icon"><ShieldCheck size={18}/></span><strong>Jawaban punya sumber.</strong><p>Kelola informasi resmi untuk percakapan yang lebih tepercaya.</p></div><button className="user-profile" onClick={async()=>{await send('/auth/logout');setSession({authenticated:false,configured:true,username:null});}}><span className="user-avatar">A</span><span><strong>Administrator</strong><small>{session.username}</small></span><LogOut size={17}/></button></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" aria-label="Buka navigasi" onClick={()=>setSidebar(true)}><Menu size={22}/></button><span>Workspace</span><span className="slash">/</span><strong>{active?.label??'Chat Playground'}</strong></div><div className="topbar-right"><span className="local-chip"><i/> Local workspace</span><span className="top-avatar">A</span></div></header><main>{page==='overview'?<Overview navigate={navigate}/>:page==='whatsapp'?<WhatsAppPage/>:page==='knowledge'?<KnowledgePage/>:page==='documents'?<DocumentsPage/>:page==='tickets'?<TicketsPage/>:page==='analytics'?<AnalyticsPage/>:page==='settings'?<SettingsPage/>:<PlaygroundPage/>}</main><footer className="main-footer"><span>TIVAsk Control Center</span><span>Dibuat untuk percakapan yang berarti.</span></footer></div></div>;
}

