import { Router } from 'express';
import multer from 'multer';
import { z } from 'zod';
import path from 'node:path';
import { env,dataPath } from '../config/env.js';
import { AppError } from '../core/errors.js';
import { prisma,db,databaseHealth } from '../core/prisma.js';
import { authenticated,configured,requireAuth,login,logout,loginLimiter } from '../middleware/auth.js';
import { knowledgeSchema } from '../modules/knowledge/types.js';
import * as services from '../container.js';
const {persistence,knowledge,gemini,vectors,conversations,whatsapp,tickets,documents,analytics}=services;
export const router=Router();
const id=(v:unknown)=>z.string().min(1).max(100).parse(v);
const reply=(res:import('express').Response,data:unknown,status=200)=>res.status(status).json({ok:true,data});
router.get('/health',async(_req,res)=>{const database=await databaseHealth();reply(res,{name:'TIVAsk',backend:'ONLINE',database,ready:database.status==='ONLINE'&&database.schema==='READY'});});
router.get('/auth/session',(req,res)=>reply(res,{authenticated:authenticated(req),configured:configured(),username:authenticated(req)?env.ADMIN_USERNAME:null}));
router.post('/auth/login',loginLimiter,(req,res)=>{const v=z.object({username:z.string().max(80),password:z.string().min(1).max(200)}).parse(req.body);login(v.username,v.password,res);reply(res,{username:env.ADMIN_USERNAME});});
router.post('/auth/logout',(req,res)=>{logout(req,res);reply(res,{loggedOut:true});});
router.use(requireAuth);
router.get('/system/status',async(_req,res)=>{const database=await databaseHealth();let indexed=0;try{indexed=await db(()=>prisma.document.count({where:{status:'INDEXED'}}));}catch{}
reply(res,{backend:'ONLINE',database,gemini:{status:gemini.status,model:env.GEMINI_MODEL,lastChecked:gemini.lastChecked},whatsapp:whatsapp.state.status,rag:{status:database.status==='ONLINE'?(indexed?'READY':'EMPTY'):'UNAVAILABLE',mode:vectors.mode,indexed},knowledgeSource:knowledge.source,pendingSync:await persistence.pending(),demoMode:env.DEMO_MODE,schoolName:env.SCHOOL_NAME,academicYear:env.ACADEMIC_YEAR});});
router.post('/system/sync',async(_req,res)=>{await persistence.sync();reply(res,{pending:await persistence.pending()});});
router.post('/system/check-gemini',async(_req,res)=>reply(res,{status:await gemini.check()}));
router.post('/chat',async(req,res)=>{const v=z.object({senderId:z.string().regex(/^sim:[a-zA-Z0-9_-]{1,60}$/),message:z.string().trim().min(1).max(2000)}).parse(req.body);reply(res,await conversations.handle(v.senderId,v.message,'SIMULATOR'));});
router.get('/conversations/:senderId',async(req,res)=>reply(res,await conversations.history(id(req.params.senderId))));
router.get('/whatsapp/status',(_req,res)=>reply(res,whatsapp.state));
router.post('/whatsapp/:action',async(req,res)=>{const action=z.enum(['connect','reconnect','disconnect','logout']).parse(req.params.action);await whatsapp[action]();reply(res,whatsapp.state);});
router.get('/knowledge',async(_req,res)=>reply(res,{items:await knowledge.load(true),source:knowledge.source}));
router.post('/knowledge',async(req,res)=>{const row=await knowledge.repository.save(knowledgeSchema.parse(req.body));knowledge.invalidate();await knowledge.load(true);reply(res,row,201);});
router.put('/knowledge/:id',async(req,res)=>{const row=await knowledge.repository.save(knowledgeSchema.parse(req.body),id(req.params.id));knowledge.invalidate();await knowledge.load(true);reply(res,row);});
router.delete('/knowledge/:id',async(req,res)=>{await knowledge.repository.remove(id(req.params.id));knowledge.invalidate();await knowledge.load(true);reply(res,{deleted:true});});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:1,fields:3}});
router.post('/documents',upload.single('file'),async(req,res)=>{if(!req.file)throw new AppError(400,'Pilih file terlebih dahulu.');reply(res,await documents.upload(req.file,req.body.verified==='true',req.body.demo==='true'),202);});
router.get('/documents',async(_req,res)=>reply(res,await db(()=>prisma.document.findMany({include:{_count:{select:{chunks:true}}},orderBy:{uploadedAt:'desc'}}))));
router.get('/documents/:id',async(req,res)=>{const row=await db(()=>prisma.document.findUnique({where:{id:id(req.params.id)},include:{chunks:{select:{id:true,chunkIndex:true,page:true,text:true,tokenCount:true,embeddingModel:true},orderBy:{chunkIndex:'asc'}}}}));if(!row)throw new AppError(404,'Dokumen tidak ditemukan.');reply(res,row);});
router.get('/documents/:id/download',async(req,res)=>{const row=await db(()=>prisma.document.findUnique({where:{id:id(req.params.id)}}));if(!row)throw new AppError(404,'Dokumen tidak ditemukan.');res.download(path.resolve(dataPath('uploads',row.storageName)),row.filename);});
router.patch('/documents/:id',async(req,res)=>{const v=z.object({verified:z.boolean()}).parse(req.body);reply(res,await db(()=>prisma.document.update({where:{id:id(req.params.id)},data:v})));});
router.post('/documents/:id/reindex',async(req,res)=>{const key=id(req.params.id);const row=await db(()=>prisma.document.findUnique({where:{id:key}}));if(!row)throw new AppError(404,'Dokumen tidak ditemukan.');documents.enqueue(key);reply(res,{queued:true},202);});
router.delete('/documents/:id',async(req,res)=>{await documents.remove(id(req.params.id));reply(res,{deleted:true});});
router.get('/tickets',async(req,res)=>{let rows=await persistence.tickets();if(req.query.status)rows=rows.filter(t=>t.status===req.query.status);if(req.query.priority)rows=rows.filter(t=>t.priority===req.query.priority);reply(res,rows);});
router.get('/tickets/:id',async(req,res)=>{const ticket=await tickets.find(id(req.params.id));reply(res,{ticket,messages:await persistence.history(ticket.conversationId,60)});});
router.patch('/tickets/:id',async(req,res)=>{const v=z.object({status:z.enum(['OPEN','IN_PROGRESS','RESOLVED']).optional(),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).optional(),name:z.string().max(100).optional()}).parse(req.body);reply(res,await tickets.update(id(req.params.id),v));});
router.post('/tickets/:id/reply',async(req,res)=>{
 const v=z.object({message:z.string().trim().min(1).max(4000),requestId:z.string().uuid()}).parse(req.body);
 const t=await tickets.find(id(req.params.id));if(!t.whatsappNumber.startsWith('sim:')&&whatsapp.state.status!=='CONNECTED')throw new AppError(409,'Hubungkan WhatsApp terlebih dahulu.');
 reply(res,await conversations.adminReply(t.id,v.message,v.requestId,(to,text)=>whatsapp.send(to,text)));
});
router.get('/analytics',async(req,res)=>reply(res,await analytics.summary(req.query.includeDemo!=='false')));
router.get('/settings',async(_req,res)=>reply(res,{schoolName:env.SCHOOL_NAME,academicYear:env.ACADEMIC_YEAR,panitiaName:env.PANITIA_NAME,panitiaWa:env.PANITIA_WA,geminiModel:env.GEMINI_MODEL,embeddingModel:env.GEMINI_EMBEDDING_MODEL,historyLimit:env.CONVERSATION_HISTORY_LIMIT,ragTopK:env.RAG_TOP_K,ragMinScore:env.RAG_MIN_SCORE,demoMode:env.DEMO_MODE,adminUsername:env.ADMIN_USERNAME}));
router.put('/settings',async(req,res)=>{const v=z.object({panitiaName:z.string().trim().min(2).max(120),panitiaWa:z.string().regex(/^(\+?[0-9]{8,16})?$/)}).parse(req.body);await db(()=>prisma.systemSetting.upsert({where:{key:'contact'},create:{key:'contact',value:v},update:{value:v}}));env.PANITIA_NAME=v.panitiaName;env.PANITIA_WA=v.panitiaWa;reply(res,v);});
router.post('/demo/reset',async(req,res)=>{
 if(!env.DEMO_MODE)throw new AppError(403,'Demo mode tidak aktif.');
 z.object({confirmation:z.literal('RESET DEMO')}).parse(req.body);
 await persistence.sync();
 await db(()=>prisma.$transaction([prisma.conversation.deleteMany({where:{channel:'SIMULATOR'}}),prisma.analyticsEvent.deleteMany({where:{demo:true}})]));
 await persistence.journal.update(s=>{const ids=new Set(s.conversations.filter(c=>c.channel==='SIMULATOR').map(c=>c.id));s.conversations=s.conversations.filter(c=>!ids.has(c.id));s.messages=s.messages.filter(m=>!ids.has(m.conversationId));s.events=s.events.filter(e=>!e.demo);});
 await persistence.ticketStore.update(s=>{s.tickets=s.tickets.filter(t=>!t.whatsappNumber.startsWith('sim:'));});
 reply(res,{reset:true});
});

